### ISSUE TITLE
Conta PF

### ISSUE THREAD

**Issue by jeffersonmsb** [lucasrcezimbra/bancointer#22]
Olá, controlo minhas finanças utilizando dados do nubank, via pynubank.

Queria integrar o inter tb. É possível obter dados de conta PF?

**Comment by lucasrcezimbra** [comment]
Opa. Olá, @jeffersonmsb.

Atualmente a API aberta do Inter é só para contas PJ:

> Depois de criar e ativar sua conta digital PJ Inter, você está apto a criar uma aplicação e usar nossas APIs.

https://developers.bancointer.com.br/docs/criar-aplicacao


Até daria para implementar a conta PF, mas precisaria fazer uma engenharia reversa no mobile ou web app.

**Comment by jeffersonmsb** [comment]
Por exemplo, usando a lib requests do python?

**Comment by jeffersonmsb** [comment]
Entendi, vou tentar pelo app pra descobrir a API.
